[env]
AUTOGROWER_SSE_URL = { value = "https://api.autogrower.eu" }
AUTOGROWER_BACKEND_API = { value = "https://api.autogrower.eu" }

[alias]
cov = "tarpaulin --out html --all-targets"
ut = "test --tests"
d = "doc --open --no-deps --document-private-items"
lint = "clippy"
